### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by Jgaleas7** [nrkno/tv-automation-media-management#6]
Error during initialization:

{"level":"error","message":"Network error: ws://127.0.0.1:3000/websocket: connect ECONNREFUSED 127.0.0.1:3000","localTimestamp":"2019-05-21T18:20:49.787Z","randomId":8506}

**Comment by jesperstarkar** [comment]
Hi.

The Media Manager device needs to be conencted to a [Sofie Core](https://github.com/nrkno/tv-automation-server-core) Server, which have it's own set of dependencies to be running.

At the moment there's no easy way of getting started with the Sofie stack, but documentation and potentially also starter setups are on its way.
